sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t7TGQpk29B1tWUKeTke
    access-key-secret: TJrF7q5gaVXsOQhaioQY7YXUxvv2eZ
    bucket-name: shibbb
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
  wechat:
    appid: wx0a55a0474e4a7c67
    secret: 5d6358a3a4bd5014418474278c50be9c

